### ISSUE TITLE
libzmq version

### ISSUE THREAD

**Issue by deadthings** [zixxcrypto/zixxcore#8]
On one of my Ubuntu 16.04 VPS servers (Vultr), libzmq5 worked fine, but on a different one (Cloud.co.za), it did not and I had to install libzmq3-dev instead.

**Comment by zixxcrypto** [comment]
Is this about the compilation process or about the binaries? 
Are both providers using Ubuntu 16.04; if so, have you updated the repository cache before installing?

**Comment by deadthings** [comment]
This was about the binaries. Compilation was, admittedly, too tricky for me to figure out at this point so I gave up. 

Yes - both providers are 16.04, and yes, both repo caches were updated. Hence the weirdness. 

I use a generally standard set of dependencies for all of my server installs:

build-essential | libboost-all-dev | libminiupnpc-dev | libevent-dev | libdb4.8-dev | libdb4.8++-dev | git | dh-autoreconf | libprotobuf-dev | libtool | autotools-dev | autoconf | pkg-config | libssl-dev | automake | bsdmainutils | protobuf-compiler | libqrencode-dev | software-properties-common | libgmp3-dev | nano | htop | pwgen

It was on top of these that I added the dependencies outlined here: https://cdn.discordapp.com/attachments/385953676973572096/444703534844477440/Zixx_Masternode_setup_guide_V0.5.odt

In the Vultr case, everything worked just fine. But in the other case, I had to add libzmq3-dev before the binary would launch, otherwise I received this error: 

error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory

**Comment by zixxcrypto** [comment]
Just ran a test with the updated docs (https://github.com/zixxcrypto/zixxcore/wiki/Platform-Specific-Environment-Set-up) on a fresh installation of Ubuntu 16.04 and it seems that everything is in order.

Occasionally, cloud providers might add extra packages/sources to a distribution, creating all sorts of chaos. I'll close this for now, since the updated docs assume a clean installation. If the problem persists, we'll revisit it.
